// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LifePuck_Project

#include "ui.h"

lv_obj_t * uic_logBack;
lv_obj_t * ui_LogScreen = NULL;
lv_obj_t * ui_logBack = NULL;
lv_obj_t * ui_Log = NULL;
// event funtions

// build funtions

void ui_LogScreen_screen_init(void)
{
    ui_LogScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LogScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logBack = lv_imgbtn_create(ui_LogScreen);
    lv_imgbtn_set_src(ui_logBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_387995924, NULL);
    lv_obj_set_width(ui_logBack, 48);
    lv_obj_set_height(ui_logBack, 48);
    lv_obj_set_x(ui_logBack, -152);
    lv_obj_set_y(ui_logBack, -193);
    lv_obj_set_align(ui_logBack, LV_ALIGN_CENTER);

    ui_Log = lv_textarea_create(ui_LogScreen);
    lv_obj_set_width(ui_Log, 350);
    lv_obj_set_height(ui_Log, 360);
    lv_obj_set_x(ui_Log, 0);
    lv_obj_set_y(ui_Log, 25);
    lv_obj_set_align(ui_Log, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Log, "Life log...");
    lv_obj_set_style_text_font(ui_Log, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_logBack = ui_logBack;

}

void ui_LogScreen_screen_destroy(void)
{
    if(ui_LogScreen) lv_obj_del(ui_LogScreen);

    // NULL screen variables
    ui_LogScreen = NULL;
    uic_logBack = NULL;
    ui_logBack = NULL;
    ui_Log = NULL;

}
