// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LifePuck_Project

#ifndef UI_LOGSCREEN_H
#define UI_LOGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LogScreen
extern void ui_LogScreen_screen_init(void);
extern void ui_LogScreen_screen_destroy(void);
extern lv_obj_t * ui_LogScreen;
extern lv_obj_t * ui_logBack;
extern lv_obj_t * ui_Log;
// CUSTOM VARIABLES
extern lv_obj_t * uic_logBack;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

