// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LifePuck_Project

#include "ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_topCutTimerEnable = NULL;
lv_obj_t * ui_topCutTimerText = NULL;
lv_obj_t * ui_settingsBack = NULL;
// event funtions

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topCutTimerEnable = lv_switch_create(ui_Settings);
    lv_obj_set_width(ui_topCutTimerEnable, 50);
    lv_obj_set_height(ui_topCutTimerEnable, 25);
    lv_obj_set_align(ui_topCutTimerEnable, LV_ALIGN_CENTER);

    ui_topCutTimerText = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_topCutTimerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_topCutTimerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_topCutTimerText, -91);
    lv_obj_set_y(ui_topCutTimerText, 1);
    lv_obj_set_align(ui_topCutTimerText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_topCutTimerText, "Top cut timer");

    ui_settingsBack = lv_imgbtn_create(ui_Settings);
    lv_imgbtn_set_src(ui_settingsBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_387995924, NULL);
    lv_obj_set_width(ui_settingsBack, 48);
    lv_obj_set_height(ui_settingsBack, 48);
    lv_obj_set_x(ui_settingsBack, -152);
    lv_obj_set_y(ui_settingsBack, -193);
    lv_obj_set_align(ui_settingsBack, LV_ALIGN_CENTER);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_topCutTimerEnable = NULL;
    ui_topCutTimerText = NULL;
    ui_settingsBack = NULL;

}
