// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LifePuck_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_timer;
extern lv_obj_t * ui_lifeUp;
extern lv_obj_t * ui_lifeDown;
extern lv_obj_t * ui_Life;
extern lv_obj_t * ui_minutes;
extern lv_obj_t * ui_Bat;
extern lv_obj_t * ui_percent;
extern lv_obj_t * ui_settingsButton;
extern lv_obj_t * ui_tempLife;
// CUSTOM VARIABLES
extern lv_obj_t * uic_settingsButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

