// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LifePuck_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Purple[1] = {0x500064};
const ui_theme_variable_t _ui_theme_alpha_Purple[1] = {255};

const ui_theme_variable_t _ui_theme_color_Red[1] = {0xFF0000};
const ui_theme_variable_t _ui_theme_alpha_Red[1] = {255};

const ui_theme_variable_t _ui_theme_color_Green[1] = {0x00FF00};
const ui_theme_variable_t _ui_theme_alpha_Green[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

