// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: LifePuck_Project

#include "ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_topCutTimerEnable = NULL;
lv_obj_t * ui_topCutTimerText = NULL;
lv_obj_t * ui_settingsBack = NULL;
lv_obj_t * ui_LogButton = NULL;
lv_obj_t * ui_logButtonLabel = NULL;
// event funtions

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_topCutTimerEnable = lv_switch_create(ui_Settings);
    lv_obj_set_width(ui_topCutTimerEnable, 70);
    lv_obj_set_height(ui_topCutTimerEnable, 35);
    lv_obj_set_x(ui_topCutTimerEnable, 90);
    lv_obj_set_y(ui_topCutTimerEnable, -100);
    lv_obj_set_align(ui_topCutTimerEnable, LV_ALIGN_CENTER);

    ui_topCutTimerText = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_topCutTimerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_topCutTimerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_topCutTimerText, -50);
    lv_obj_set_y(ui_topCutTimerText, -100);
    lv_obj_set_align(ui_topCutTimerText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_topCutTimerText, "Top cut timer");
    lv_obj_set_style_text_font(ui_topCutTimerText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsBack = lv_imgbtn_create(ui_Settings);
    lv_imgbtn_set_src(ui_settingsBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_387995924, NULL);
    lv_obj_set_width(ui_settingsBack, 48);
    lv_obj_set_height(ui_settingsBack, 48);
    lv_obj_set_x(ui_settingsBack, -152);
    lv_obj_set_y(ui_settingsBack, -193);
    lv_obj_set_align(ui_settingsBack, LV_ALIGN_CENTER);

    ui_LogButton = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_LogButton, 70);
    lv_obj_set_height(ui_LogButton, 70);
    lv_obj_set_x(ui_LogButton, -85);
    lv_obj_set_y(ui_LogButton, -6);
    lv_obj_set_align(ui_LogButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LogButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_LogButton, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logButtonLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_logButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logButtonLabel, -3);
    lv_obj_set_y(ui_logButtonLabel, -6);
    lv_obj_set_align(ui_logButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_logButtonLabel, "Log");
    lv_obj_set_style_text_font(ui_logButtonLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_topCutTimerEnable = NULL;
    ui_topCutTimerText = NULL;
    ui_settingsBack = NULL;
    ui_LogButton = NULL;
    ui_logButtonLabel = NULL;

}
